#+title: F2

Computeren er redskab til at teste teorier i datalogi

* Kudos
Kudos - giv videnskab penge og videnskab giver nyttigt til samfundet

* Den lineære model
+ Skridder et skridt af gangen
+ Samlebpndsmodellen
+ Hvert skridt følger naturligt hinanden
+ Innovation fase
  + Mere kompleks end den linære model antyder
  + Videnskabelse
+ Entrpenør fase
  + Værdiskabelse
+ Hvad har ansvaret for hvad der blev produceret

* Stokes kvadrantmodel
Fire kvadranter
+ Ren grundvidenskab - Bohr kvadant
+ Ren anvendelse - edison
+ Blanding af de ovestående - Pasteur
+ Ingen af delene

* Formålsdimension
+ Hvad er motivation for at gøre det
+ Bohr gør det for interessen
+ Edison gør det for at tjene penge
+ Brugt som kritik af den linære model

* Temporal(tidslig) dimension

* Kausal dimension

* Epistemologisk dimension
+ Grundvidenskab - hvad er interessant. Hvad er sandhed
+ Teknologisk - hvad kan bruges. Pragmatisk. Handlingsorienteret.
To forskellige epistemologier - erkendelser

Også dårligt, for når vi laver grundvidenskab er der også et pragmatisk aspekt over hvorfor vi forsker i det.

* Teknologiske systemer
Teknologier skaber de samfund og strukturer de indgår i.

** komponenter
+ Viden
+ Artefakter
+ Jura
+ Organizationer

Ændring af et hjørne af netværket vil påvirke alle andre hjørner.
* Eksempel
Computeren er ikke en prædetermineret process.
Den er åben for en masse valg. Som hugh også sagde - den er social konstrueret og kan ændre.

Det er ikke en teknologisk determinisme at computeren ville blive mindre og at vi får PC.

** Elementer
+ Fysiske artefakter - firmaerne
+ Organizationer
+ Videnskabelige
+ Juridisk og regulerende (cypyright)
+ Naturressourcer (sjældne jordarter)
Godt eksempel teknologisk teknologi forståelse er altså PC

Betragt ikke teknologi som artefakter, men systemer der er forbundne

* Teknologi som systemer
+ Ikke bare artefakter
+ Heterogent netværk
+ Forskellige noder i netværket kan antage forskellige roller
  + Translation - nogle hjørner kan være repræsentanter for noget. Industristandarder

+ Konservativ opfindelse
  + Små forbedringer
+ Radikale opfindelse
  + Store forbedringer.
  + Det teknologiske system skabes sammen med teknologien
  + PC ændrede arbejdspraksis
+ Definerende teknologier der skaber virkeligheden
  + Radikale teknologier
  + Så radikalt forandrede at hele verdenssynet forandres

Er det ekperimentet der viser en virkelighed eller er det arparatet der måler forkert. Valget er social konstruktivistisk.
Videnskab er en process hængt op på mennesker og ikke en ekstern virkelighed. Indvening mod popper og logisk positivister.
